schools = [
    # dict(name='Adelson Educational Campus', code=1, testedGradeCount=3, sector=3,
    #      grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Barrack Hebrew Academy', code=45, testedGradeCount=2, sector=3, grades={'5th': 0, '8th': 1, '11th': 1}),
    # dict(name='Ben Porat Yosef', code=3, testedGradeCount=2, sector=1, grades={'5th': 1, '8th': 1, '11th': 0}),
    dict(name='Berman Hebrew Academy', code=4, testedGradeCount=3, sector=1, grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Beth Tfiloh', code=44, testedGradeCount=3, sector=1, grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Bialik Hebrew Day School', code=5, testedGradeCount=2, sector=3, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Boston-JCDS', code=40, testedGradeCount=2, sector=3, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Carmel Academy', code=41, testedGradeCount=2, sector=3, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Charles E Smith Jewish Day School', code=6, testedGradeCount=3, sector=2,
    #      grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Denver Academy of Torah', code=8, testedGradeCount=3, sector=1, grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Donna Klein Jewish Academy', code=9, testedGradeCount=3, sector=3,
    #      grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Hannah Senesh Community Day School', code=11, testedGradeCount=2, sector=3,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Harkham Hillel Hebrew Academy', code=12, testedGradeCount=2, sector=1,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Hillel Torah North Suburban Day School', code=13, testedGradeCount=2, sector=1,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Jewish community High school of the Bay', code=14, testedGradeCount=1, sector=3,
    #      grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Maayanot Yeshiva High School for Girls', code=15, testedGradeCount=1, sector=1,
    #      grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Mandel JDS', code=16, testedGradeCount=2, sector=3, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Robert M. Beren Academy', code=18, testedGradeCount=3, sector=1, grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Rochelle Zelle High School', code=42, testedGradeCount=1, sector=3,
    #      grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='SAR Academy', code=19, testedGradeCount=2, sector=1, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='SAR High School', code=20, testedGradeCount=1, sector=1, grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Schechter School of Long Island', code=21, testedGradeCount=3, sector=2,
    #      grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Schechter Westchester', code=22, testedGradeCount=3, sector=2, grades={'5th': 1, '8th': 1, '11th': 1}),
    # dict(name='Shulamith School for Girls', code=23, testedGradeCount=2, sector=1,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='SKA High School', code=43, testedGradeCount=1, sector=1, grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Solomon Schechter Day School Las Vegas', code=24, testedGradeCount=1, sector=2,
    #      grades={'5th': 1, '8th': 0, '11th': 0}),
    # dict(name='Solomon Schechter School of Manhattan', code=25, testedGradeCount=2, sector=2,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='TanenbaumCHAT', code=27, testedGradeCount=1, sector=3, grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='The Brandeis School of San Frnacisco', code=28, testedGradeCount=2, sector=3,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='The Epstein School', code=29, testedGradeCount=2, sector=2, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='The Rashi School', code=30, testedGradeCount=2, sector=3, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='The Shlenker School', code=31, testedGradeCount=1, sector=3, grades={'5th': 1, '8th': 0, '11th': 0}),
    # dict(name='The Weber School', code=32, testedGradeCount=1, sector=3, grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Weinbaum Yeshiva High School', code=33, testedGradeCount=1, sector=1,
    #      grades={'5th': 0, '8th': 0, '11th': 1}),
    # dict(name='Wornick Jewish Day School', code=34, testedGradeCount=2, sector=3,
    #      grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Yavneh Academy', code=35, testedGradeCount=2, sector=1, grades={'5th': 1, '8th': 1, '11th': 0}),
    # dict(name='Yeshiva of Greater Washington', code=37, testedGradeCount=2, sector=1,
    #      grades={'5th': 0, '8th': 1, '11th': 1}),
    # dict(name='Yeshivat Har Torah', code=36, testedGradeCount=2, sector=1, grades={'5th': 1, '8th': 1, '11th': 0})
]